version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10 # This will install python 3.10 on the enviroment ec2
    commands:
      - echo == INSTALL YOUR PACKAGES HERE!!! ===

  pre_build:
    commands:
       - echo == CHECKING FOR PYTHON INSTALL ===
       - python3 --version
       - echo === CHECKING FOR PYTHON INSTALL ===
       - aws --version    
  build:
    commands:
      - echo === RUN OUR CODE/APP ===
      - python3 my_app.py # This is going th run the python app prensent in my_app.py
      
  post_build:
    commands:
      - echo === ACTION TO TAKE WHEN BUILD IS COMPLETE
      - echo Build completed at `date' ...

artifacts:
  files:
    - '**/*' # this will grab everything an zip it 